services:
  mydb:
    image: mariadb:latest
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - 4450:3306
    command: --innodb_flush_log_at_trx_commit=2
    networks:
      - bot-net
    restart: always
  gobot:
    image: golang:alpine
    container_name: gobot
    working_dir: /bot
    env_file:
      - .env
    volumes:
      - ./bot:/bot
    command: go run .
    networks:
      - bot-net
    depends_on:
      - mydb
    restart: always
networks:
  bot-net:
    driver: bridge
