FROM golang:alpine AS builder
WORKDIR /bot
COPY ./bot .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o gobot .

FROM alpine:latest
WORKDIR /bot
COPY --from=builder /bot/gobot .
CMD ["./gobot"]
