FROM golang:alpine AS builder
WORKDIR /bot
COPY bot/go.mod bot/go.sum ./
RUN go mod download
COPY bot/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o gobot .

FROM alpine:latest
WORKDIR /bot
COPY --from=builder /bot/gobot .
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown appuser:appgroup /bot
USER appuser
CMD ["./gobot"]
